"use client";

import React from "react";
import dynamic from "next/dynamic";
import { motion, AnimatePresence } from "framer-motion";
import { VisualizationConfig, AnalysisState } from "@/types/api";
import { BarChart3, Info } from "lucide-react";

// SSR-safe Plotly import
const Plot = dynamic(() => import("react-plotly.js"), { ssr: false });

const DARK_NEON_PALETTE = [
  "#22C55E", // Emerald Green
  "#06B6D4", // Bright Cyan
  "#A855F7", // Purple
  "#EC4899", // Magenta
  "#F59E0B", // Amber
  "#38BDF8", // Light Blue
  "#F43F5E", // Coral Rose
];

interface DynamicChartRendererProps {
  visualizations: VisualizationConfig[];
  analysisState: AnalysisState;
}

export function DynamicChartRenderer({ visualizations, analysisState }: DynamicChartRendererProps) {
  const preview = analysisState.preview_data || [];
  const stats = analysisState.column_statistics || {};

  const buildPlotData = (config: VisualizationConfig) => {
    const { chart_type, x_column, y_column } = config;

    let xData: any[] = [];
    let yData: any[] = [];

    if (preview.length > 0) {
      xData = preview.map((row) => row[x_column]).filter((v) => v !== undefined);
      if (y_column) {
        yData = preview.map((row) => row[y_column]).filter((v) => v !== undefined);
      }
    } else {
      const colStat = stats[x_column];
      if (colStat?.categorical?.top_categories) {
        xData = Object.keys(colStat.categorical.top_categories);
        yData = Object.values(colStat.categorical.top_categories);
      } else if (colStat?.numeric) {
        xData = ["min", "mean", "max"];
        yData = [colStat.numeric.min, colStat.numeric.mean, colStat.numeric.max];
      }
    }

    const typeMap: Record<string, string> = {
      bar: "bar",
      line: "scatter",
      scatter: "scatter",
      histogram: "histogram",
      box: "box",
      pie: "pie",
    };

    const plotlyType = typeMap[chart_type] || "bar";
    const mode = chart_type === "line" ? "lines+markers" : chart_type === "scatter" ? "markers" : undefined;

    if (chart_type === "pie") {
      return [
        {
          labels: xData,
          values: yData.length > 0 ? yData : Array(xData.length).fill(1),
          type: "pie" as const,
          marker: { colors: DARK_NEON_PALETTE },
        },
      ];
    }

    return [
      {
        x: xData,
        y: yData.length > 0 ? yData : undefined,
        type: plotlyType as any,
        mode: mode,
        marker: { color: "#22C55E" },
      },
    ];
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
      className="dark-surface-card rounded-2xl p-6 shadow-2xl my-6 border border-white/[0.08]"
    >
      <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/[0.08]">
        <div className="p-2.5 bg-[#22C55E]/15 border border-[#22C55E]/30 text-[#22C55E] rounded-xl">
          <BarChart3 className="w-5 h-5" />
        </div>
        <div>
          <h3 className="text-lg font-bold text-white tracking-tight">Recommended Interactive Plotly Charts</h3>
          <p className="text-xs text-slate-400">Structured chart specifications generated by AI Visualization Agent</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <AnimatePresence initial={false}>
          {visualizations.map((config, idx) => (
            <motion.div
              key={config.title + idx}
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
              className="bg-[#0B0F19]/80 border border-white/[0.08] rounded-xl p-5 flex flex-col hover:border-[#22C55E]/40 transition"
            >
              {/* Chart Header */}
              <div className="mb-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-sm font-bold text-white">{config.title}</h4>
                  <span className="text-[10px] uppercase font-bold px-2.5 py-0.5 rounded-full bg-[#22C55E]/15 text-[#22C55E] border border-[#22C55E]/30">
                    {config.chart_type}
                  </span>
                </div>
                <p className="text-xs text-slate-400 mt-1">{config.description}</p>
                {config.justification && (
                  <div className="mt-2.5 pt-2 border-t border-white/[0.06] flex items-start gap-2 bg-white/[0.02] p-2.5 rounded-lg border border-white/[0.04]">
                    <Info className="w-3.5 h-3.5 text-[#22C55E] shrink-0 mt-0.5" />
                    <p className="text-[11px] text-slate-300 italic leading-snug">
                      <span className="font-semibold text-slate-200 not-italic">Design Rationale: </span>
                      {config.justification}
                    </p>
                  </div>
                )}
              </div>

              {/* Plotly Canvas Container */}
              <div className="w-full h-72 flex-1 rounded-xl overflow-hidden bg-black/40 flex items-center justify-center border border-white/[0.04] p-2">
                <Plot
                  data={buildPlotData(config)}
                  layout={{
                    autosize: true,
                    margin: { l: 40, r: 20, t: 20, b: 40 },
                    paper_bgcolor: "transparent",
                    plot_bgcolor: "transparent",
                    font: { color: "#F8FAFC", size: 11, family: "Inter, sans-serif" },
                    xaxis: { gridcolor: "rgba(255,255,255,0.06)", title: config.x_column },
                    yaxis: { gridcolor: "rgba(255,255,255,0.06)", title: config.y_column || "" },
                  }}
                  useResizeHandler={true}
                  className="w-full h-full"
                  config={{ responsive: true, displayModeBar: false }}
                />
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

